-- Migration: Seed pacientes table with sample data
-- Description: Inserts 8 sample patients with variety in age, gender, and insurance coverage
-- Date: 2025-11-15

-- Insert sample patients
-- Note: obra_social_id is retrieved via subquery to ensure referential integrity
INSERT INTO public.pacientes (
    dni,
    nombre,
    apellido,
    fecha_nacimiento,
    genero,
    telefono,
    email,
    domicilio,
    obra_social_id,
    plan,
    numero_afiliado,
    estado,
    consentimiento_datos,
    notas,
    created_by,
    updated_by
) VALUES
(
    '32456789',
    'María',
    'González',
    '1986-03-15',
    'F',
    '5491145678901',
    'maria.gonzalez@email.com',
    'Av. Santa Fe 2450, CABA',
    (SELECT id FROM public.obras_sociales WHERE nombre = 'OSDE' LIMIT 1),
    'OSDE 310',
    '3245678901',
    'activo',
    true,
    'Paciente regular. Antecedentes de dermatitis atópica.',
    NULL,
    NULL
),
(
    '28345678',
    'Carlos',
    'Rodríguez',
    '1980-07-22',
    'M',
    '5491145678902',
    'carlos.rodriguez@email.com',
    'Av. Corrientes 1234, CABA',
    (SELECT id FROM public.obras_sociales WHERE nombre = 'Swiss Medical' LIMIT 1),
    'SMG 50',
    '2834567802',
    'activo',
    true,
    'Control anual preventivo.',
    NULL,
    NULL
),
(
    '41234567',
    'Ana',
    'Martínez',
    '1998-11-08',
    'F',
    '5491145678903',
    'ana.martinez@email.com',
    'Av. Cabildo 3890, CABA',
    (SELECT id FROM public.obras_sociales WHERE nombre = 'Galeno' LIMIT 1),
    'Galeno 330',
    '4123456703',
    'activo',
    true,
    'Tratamiento de acné. Seguimiento mensual.',
    NULL,
    NULL
),
(
    '16789012',
    'Roberto',
    'Fernández',
    '1963-05-30',
    'M',
    '5491145678904',
    'roberto.fernandez@email.com',
    'Av. Rivadavia 5678, CABA',
    (SELECT id FROM public.obras_sociales WHERE nombre = 'PAMI' LIMIT 1),
    'PAMI Básico',
    '1678901204',
    'activo',
    true,
    'Control de lunares. Historia familiar de cáncer de piel.',
    NULL,
    NULL
),
(
    '35678901',
    'Laura',
    'Pérez',
    '1990-09-12',
    'F',
    '5491145678905',
    'laura.perez@email.com',
    'Av. Belgrano 2200, CABA',
    (SELECT id FROM public.obras_sociales WHERE nombre = 'IOMA' LIMIT 1),
    'IOMA Integral',
    '3567890105',
    'activo',
    true,
    'Empleada pública provincial. Psoriasis leve.',
    NULL,
    NULL
),
(
    '44567890',
    'Diego',
    'Silva',
    '2002-01-25',
    'M',
    '5491145678906',
    'diego.silva@email.com',
    'Av. Callao 1500, CABA',
    (SELECT id FROM public.obras_sociales WHERE nombre = 'Particular' LIMIT 1),
    'Particular',
    NULL,
    'activo',
    true,
    'Paciente particular. Pago de consulta en efectivo.',
    NULL,
    NULL
),
(
    '23456789',
    'Carmen',
    'López',
    '1975-12-03',
    'F',
    '5491145678907',
    'carmen.lopez@email.com',
    'Av. Pueyrredón 890, CABA',
    (SELECT id FROM public.obras_sociales WHERE nombre = 'Swiss Medical' LIMIT 1),
    'SMG 70',
    '2345678907',
    'activo',
    true,
    'Tratamiento antienvejecimiento. Consultas trimestrales.',
    NULL,
    NULL
),
(
    '38901234',
    'Javier',
    'Morales',
    '1994-06-18',
    'M',
    '5491145678908',
    'javier.morales@email.com',
    'Av. Las Heras 3456, CABA',
    (SELECT id FROM public.obras_sociales WHERE nombre = 'Galeno' LIMIT 1),
    'Galeno 220',
    '3890123408',
    'activo',
    true,
    'Dermatitis seborreica. Tratamiento en curso.',
    NULL,
    NULL
)
ON CONFLICT (dni) DO NOTHING;

-- Add comment about seed data
COMMENT ON TABLE public.pacientes IS 'Stores patient information and demographics. Seeded with 8 sample patients covering different age ranges, genders, and insurance providers.';
