-- Migration: Create booking_tokens table for WhatsApp appointment booking
-- Purpose: Store secure, single-use tokens generated by n8n agent for patient booking

-- Create booking_tokens table
CREATE TABLE booking_tokens (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  token TEXT UNIQUE NOT NULL DEFAULT gen_random_uuid()::text,
  paciente_id UUID NOT NULL REFERENCES pacientes(id) ON DELETE CASCADE,
  medico_id UUID NOT NULL REFERENCES medicos(id) ON DELETE CASCADE,
  phone_number TEXT,
  expires_at TIMESTAMPTZ NOT NULL,
  used_at TIMESTAMPTZ,
  consulta_id UUID REFERENCES consultas(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for fast token lookups (critical for public booking page)
CREATE INDEX idx_booking_tokens_token ON booking_tokens(token);

-- Index for cleanup queries (expired/used tokens)
CREATE INDEX idx_booking_tokens_expires_at ON booking_tokens(expires_at);

-- Enable Row Level Security
ALTER TABLE booking_tokens ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Allow public read access for valid tokens
-- This allows the public booking page to validate tokens without authentication
CREATE POLICY "booking_tokens_public_read" ON booking_tokens
  FOR SELECT
  USING (true);

-- RLS Policy: Allow service role to insert tokens (n8n uses service_role key)
-- Regular users cannot insert tokens directly
CREATE POLICY "booking_tokens_service_insert" ON booking_tokens
  FOR INSERT
  WITH CHECK (true);

-- RLS Policy: Allow service role to update tokens (mark as used)
CREATE POLICY "booking_tokens_service_update" ON booking_tokens
  FOR UPDATE
  USING (true)
  WITH CHECK (true);

-- RLS Policy: Allow authenticated users (staff) to view all tokens
-- This enables admin oversight and debugging
CREATE POLICY "booking_tokens_authenticated_read" ON booking_tokens
  FOR SELECT
  TO authenticated
  USING (true);

-- Add table comment
COMMENT ON TABLE booking_tokens IS 'Secure booking tokens generated by WhatsApp agent for appointment scheduling';
COMMENT ON COLUMN booking_tokens.token IS 'Unique token for booking link (UUID string)';
COMMENT ON COLUMN booking_tokens.paciente_id IS 'Patient who will book the appointment';
COMMENT ON COLUMN booking_tokens.medico_id IS 'Doctor selected by patient via WhatsApp';
COMMENT ON COLUMN booking_tokens.phone_number IS 'WhatsApp phone number for reference';
COMMENT ON COLUMN booking_tokens.expires_at IS 'Token expiration (typically 24h after creation)';
COMMENT ON COLUMN booking_tokens.used_at IS 'Timestamp when token was used to complete booking';
COMMENT ON COLUMN booking_tokens.consulta_id IS 'Reference to created appointment after successful booking';
